/**
 * Distinguishes genuine user-authored natural language from machine-injected
 * records before semantic projection. Deterministic metrics keep Claude-compatible
 * counting; this filter only shapes the audit/analysis transcript surface.
 */

const MACHINE_ONLY_TAGS = [
  'system-reminder',
  'command-name',
  'command-message',
  'command-args',
  'local-command-stdout',
  'local-command-stderr',
  'local-command-caveat',
  'local-command',
  'environment_context',
  'env_context'
];

const MACHINE_TAG_RE = new RegExp(`<(${MACHINE_ONLY_TAGS.join('|')})(?:\\s[^>]*)?>[\\s\\S]*?<\\/\\1>`, 'gi');
const SELF_CLOSING_MACHINE_TAG_RE = new RegExp(`<(${MACHINE_ONLY_TAGS.join('|')})(?:\\s[^>]*)?\\/>`, 'gi');
const INTERRUPT_RE = /^\s*\[Request interrupted by user[^\]]*\]\s*/i;
const FILLER_ONLY_RE = /^(continue|ok|yes|y|n|no|thanks|thank you|请继续|继续|好的|可以)\s*[.。!！？]*$/i;

function firstString(...values) {
  return values.find((value) => typeof value === 'string' && value.trim())?.trim() ?? null;
}

function stripMachineMarkup(text) {
  return String(text ?? '')
    .replace(MACHINE_TAG_RE, ' ')
    .replace(SELF_CLOSING_MACHINE_TAG_RE, ' ')
    .replace(/\u0000/g, ' ')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/[ \t]{2,}/g, ' ')
    .trim();
}

function looksLikeInjectedInstructionBlob(text) {
  const value = String(text ?? '');
  if (!value) return false;
  if (/^\s*#+\s*AGENTS\.md\b/im.test(value) || /^\s*AGENTS\.md\b/im.test(value)) return true;
  if (/^\s*---\s*\nname:\s*.+\ndescription:\s*/i.test(value) && /\bSKILL\.md\b|\bskill\b/i.test(value)) return true;
  if (/<agents(?:_|\s|-)?instructions?\b/i.test(value)) return true;
  if (/^\s*Caveat:\s+The messages below were generated by the user while running local commands\b/i.test(value)) return true;
  return false;
}

export function extractGenuineUserText(raw) {
  if (typeof raw !== 'string') return null;
  let text = raw;
  if (INTERRUPT_RE.test(text)) {
    text = text.replace(INTERRUPT_RE, '').trim();
    if (!text || FILLER_ONLY_RE.test(text)) return null;
  }
  text = stripMachineMarkup(text);
  if (!text) return null;
  if (looksLikeInjectedInstructionBlob(text)) return null;
  return text;
}

export function recordIsMachineLifecycle(record) {
  if (!record || typeof record !== 'object' || Array.isArray(record)) return true;
  const recordType = String(record.type ?? '').toLowerCase();
  if (recordType === 'event_msg' || recordType === 'system' || recordType === 'progress') return true;
  if (record.isMeta === true || record.isCompactSummary === true) return true;
  return false;
}

function contentBlocks(content) {
  if (typeof content === 'string') return [{ type: 'text', text: content }];
  if (!Array.isArray(content)) return [];
  return content.filter((block) => block && typeof block === 'object');
}

export function genuineUserTextFromContent(content) {
  const blocks = contentBlocks(content);
  if (blocks.length === 0) return null;
  const textParts = [];
  for (const block of blocks) {
    const type = String(block.type ?? '').toLowerCase();
    if (type === 'tool_result') continue;
    if (!['text', 'input_text', 'output_text'].includes(type)) continue;
    const genuine = extractGenuineUserText(block.text);
    if (genuine) textParts.push(genuine);
  }
  return textParts.join('\n').trim() || null;
}

export function classifyAnalysisRole(record) {
  if (recordIsMachineLifecycle(record)) return { role: null, reason: 'lifecycle' };
  const payload = record.payload && typeof record.payload === 'object' ? record.payload : null;
  const message = record.message && typeof record.message === 'object' ? record.message : null;
  const item = record.type === 'response_item' && payload ? payload : message ?? payload ?? record;
  const role = String(item.role ?? record.role ?? '').toLowerCase();
  const recordType = String(record.type ?? '').toLowerCase();
  const itemType = String(item.type ?? '').toLowerCase();

  if (role === 'system' || role === 'developer') return { role: null, reason: 'system_injection' };
  if (/(tool_use|tool_call|function_call|custom_tool_call)/.test(itemType)) {
    return { role: 'tool', name: firstString(item.name, item.tool_name, item.function?.name, 'unknown') };
  }
  if (role === 'assistant' || recordType === 'assistant' || itemType === 'assistant_message') {
    return { role: 'assistant', content: item.content };
  }
  if (role === 'user' || recordType === 'user' || itemType === 'user_message') {
    const text = genuineUserTextFromContent(item.content);
    if (!text) return { role: null, reason: 'non_user_authored' };
    return { role: 'user', text };
  }
  return { role: null, reason: 'unsupported' };
}

export function authorshipCoverageNote(source) {
  if (source === 'cursor') {
    return 'Cursor authorship filtering is experimental: private formats may mix injected context with user text, so some non-user content may still reach semantic analysis.';
  }
  return null;
}
